# Generated by Django 3.2.4 on 2021-06-10 08:55
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
    ]
