# Generated by Django 2.2.15 on 2020-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('code', models.CharField(max_length=10, verbose_name='Codi 10')),
                ('name_order', models.CharField(max_length=250, verbose_name='ordenació alfabètica')),
                ('name', models.CharField(max_length=250, verbose_name='municipi')),
                ('county', models.CharField(max_length=250, verbose_name='comarca')),
                ('county_code', models.CharField(max_length=10, verbose_name='codi comarca')),
                ('province', models.CharField(max_length=250, verbose_name='província')),
                ('province_code', models.CharField(max_length=10, verbose_name='codi província')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='codi postal')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
                'ordering': ['name_order'],
            },
        ),
    ]
