# Generated by Django 2.2.15 on 2020-09-09 14:01
import csv

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def import_cities(apps, schema_editor):
    print('')
    print("Populating cities from CSV...")
    city_m = apps.get_model('cities', 'City')
    path = settings.BASE_DIR + "/apps/cities/fixtures/tots_ens.csv"
    with open(path, encoding='iso-8859-1') as f:
        reader = csv.reader(f, doublequote=True, delimiter=';')
        for row in tqdm(reader, "Populating City"):
            if row[0] == "CODI_10":
                continue
            obj, created = city_m.objects.get_or_create(
                code=row[0],
                defaults={
                    'code': row[0],
                    'name_order': row[1],
                    'name': row[4],
                    'county': row[17],
                    'county_code': row[18],
                    'province': row[19],
                    'province_code': row[20],
                    'postal_code': f"{row[28]:>05}",
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_cities),
    ]
