version: "3.5"

networks:
  develop_project_name_network:
    name: develop_project_name_network

services:
  # http://127.0.0.1:8000 or http://localhost:8000
  develop_project_name_app:
    restart: on-failure
    container_name: develop_project_name_app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    environment:
      - DEBUG=true
      - SECRET_KEY=
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - ABSOLUTE_URL=http://localhost:8000
      # DB
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      # SMTP
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_USE_SSL=false
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - MAILING_MANAGER_DEFAULT_FROM=
      # Wasabi cloud storage configuration
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_STORAGE_BUCKET_NAME=
      - AWS_S3_ENDPOINT_URL=
      - AWS_DEFAULT_ACL=public-read
      - AWS_S3_BASE_DOMAIN=s3.eu-central-1.wasabisys.com
      - AWS_PUBLIC_MEDIA_LOCATION=media/public
      - AWS_PRIVATE_MEDIA_LOCATION=media/private
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
    depends_on:
      - develop_project_name_db
    networks:
      - develop_project_name_network

  # http://localhost:8080/
#  develop_project_name_adminer:
#    container_name: develop_project_name_adminer
#    image: adminer
#    ports:
#      - 9876:8080
#    depends_on:
#      - develop_project_name_rb
#    networks:
#      - develop_project_name_network

  develop_project_name_db:
    container_name: develop_project_name_db
    image: postgres:12.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - develop_project_name_network

  develop_project_name_nginx:
    container_name: develop_project_name_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../:/srv
    ports:
      # To run multiple projects at once, change it to 8001:80 etc.
      - 8001:80
    depends_on:
      - develop_project_name_app
    networks:
      - develop_project_name_network

